apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-clusterV1
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 1
    volumeSize: 8
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: t3.micro
    desiredCapacity: 1
    volumeSize: 8
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub